Assoconnect AbsolutePercentValueBundle Clara
assoconnect/absolute-percent-value-bundle pull request #1
Opened 2020-12-11 16:23 UTC by clarani

2020-12-11 16:41 UTC, mathieu-bourlet requested changes

2020-12-11 16:41 UTC, mathieu-bourlet commented on src/Resources/config/services.yaml
> +      - 'serializer.normalizer'
ajouter un retour à la ligne

2020-12-11 16:41 UTC, mathieu-bourlet commented on src/Resources/config/services.yaml
> +  AssoConnect\AbsolutePercentValueBundle\Normalizer:
`AssoConnect\AbsolutePercentValueBundle\Normalizer\ValueNormalizer` plutot non ?

2020-12-11 16:41 UTC, mathieu-bourlet commented on src/Object/Value.php
> +        // check type is valid
Je pense qu'on peut se passer des commentaires avec la clarté des Assertion :P

2020-12-11 16:41 UTC, mathieu-bourlet commented on src/Normalizer/ValueNormalizer.php
> +            'value' => preg_replace('/\s+/', '', $object->getValue())
Avec les assertion empechant de creer des mauvaise valeur on a besoin d'autre chose que getValue ?

2020-12-11 16:41 UTC, mathieu-bourlet commented on src/Normalizer/ValueNormalizer.php
> +            return '' === $data || null === $data ? null : new Value($data['type'], $data['value']);
Je suis pas sur que l'accés à un element de tableau non existant throw une exception.

2020-12-11 16:42 UTC, clarani commented on src/Normalizer/ValueNormalizer.php
> +            'value' => preg_replace('/\s+/', '', $object->getValue())
Hum non, j'enlève ça :)

2020-12-11 16:49 UTC, clarani commented on src/Object/Value.php
> +        // check type is valid
D'accord :'(

2020-12-11 16:49 UTC, clarani commented on src/Normalizer/ValueNormalizer.php
> +            return '' === $data || null === $data ? null : new Value($data['type'], $data['value']);
Si c'est bon, je l'ai testé dans les tests unitaires

2020-12-11 16:49 UTC, clarani commented on src/Resources/config/services.yaml
> +  AssoConnect\AbsolutePercentValueBundle\Normalizer:
Yes

2020-12-15 09:25 UTC, mathieu-bourlet approved these changes

2020-12-15 09:26 UTC, merged